# This file was generated by GoReleaser. DO NOT EDIT.
class S5cmd < Formula
  desc "Parallel S3 and local filesystem execution tool"
  homepage "https://github.com/igungor/s5cmd"
  version "0.7.9"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/igungor/s5cmd/releases/download/v0.7.9/s5cmd_0.7.9_macOS-64bit.tar.gz"
    sha256 "049e4be55b0fc162a2015a66d1ae68b6139e597a5433d82a281dac0301bf9ae4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/igungor/s5cmd/releases/download/v0.7.9/s5cmd_0.7.9_Linux-64bit.tar.gz"
      sha256 "4d065f20031f602fa317977f425c9d7c1d7b8ea0712bc50e922a4631dcccc84d"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/igungor/s5cmd/releases/download/v0.7.9/s5cmd_0.7.9_Linux-arm64.tar.gz"
        sha256 "b783fa213169e2d0e8b843fbcc3f64bb1d74532499b6442f83171ded71ab65e2"
      else
        url "https://github.com/igungor/s5cmd/releases/download/v0.7.9/s5cmd_0.7.9_Linux-armv6.tar.gz"
        sha256 "038fa2b91f0ad2fe4ac61e98b77e3d8f8e52e46904c31aa55eb1f2324f633363"
      end
    end
  end

  def install
    bin.install "s5cmd"
  end

  test do
    system "#{bin}/s5cmd -v"
  end
end
